services:

 # backend components
  catalogue:
    build: ./catalogue
    image: rajuuradi/catalogue:1.0.0
    container_name: catalogue
    depends_on:
     - mongodb

  user:
    build: ./user
    image: rajuuradi/user:1.0.0
    container_name: user
    depends_on:
     - mongodb
     - redis
     
  cart:
    build: ./cart
    image: rajuuradi/cart:1.0.0
    container_name: cart
    depends_on:
     - redis
     - catalogue

  shipping:
   build: ./shipping
   image: rajuuradi/shipping:1.0.0
   container_name: shipping
   depends_on:
   - mysql
   - cart

  payment:
   build: ./payment
   image: rajuuradi/payment:1.0.0
   container_name: payment
   depends_on:
   - cart
   - user
   - rabbitmq

  
# databases

  redis:
   image: redis:7
   container_name: redis 
   volumes:
    - redis:/data 

  mongodb: 
    build: ./mongodb
    image: rajuuradi/mongodb:1.0.0
    container_name: mongodb
    volumes:
     - mongodb:/data/db


  mysql:
   build: ./mysql
   image: rajuuradi/mysql:1.0.0
   container_name: mysql
   volumes:
    - mysql:/var/lib/mysql

  rabbitmq:
   image: rabbitmq:3
   environment:
    RABBITMQ_DEFAULT_USER: "roboshop"
    RABBITMQ_DEFAULT_PASS: "roboshop123"
   container_name: rabbitmq
   volumes:
    - rabbitmq:/var/lib/rabbitmq

 # frontend 

  frontend:
    build: ./frontend
    image: rajuuradi/frontend:1.0.0
    container_name: frontend  
    ports:
     - "80:80"  
    depends_on:
     - catalogue
     - user
     - cart
     - payment
     - shipping


networks:
  default:
    driver: bridge
    name: roboshop
    external: false

volumes:
 mongodb
 rabbitmq
 mysql
 redis